In [1]:
# Experiment No: 5

In [2]:
#AIM : creating dimensional array

In [12]:
# Name: Shraddha Sonekar
# Roll no: 58
# Sec:  CSE-DS
# Subject:ET-I


In [4]:
import numpy as np

In [5]:
# Creating 1D array. (square bracketin round = array)(square bracket=tuple)
a1=np.array([10,20,30,40])

In [6]:
a1

array([10, 20, 30, 40])

In [7]:
#Creating 2D array
a2=np.array([[11,30,20,40],[34,89,47,34]])

In [8]:
a2

array([[11, 30, 20, 40],
       [34, 89, 47, 34]])

In [10]:
#Creating 2D array using matrix
a3=np.matrix('11,23;33,45;67,78')
print(a3)
             

[[11 23]
 [33 45]
 [67 78]]


In [11]:
#Creating array of 25 random interger between 20 and 23 (inclusive)
arr=np.random.randint(20,24,size=25)
print(arr)

[22 21 20 23 22 20 21 21 22 23 21 23 21 23 21 22 20 20 22 22 20 20 20 20
 23]
